### ISSUE TITLE
field "lovedLanguagesByname_aggregate" not found in type: 'programming_language'

### ISSUE THREAD

**Issue by studuino** [thezjy/hasura-vote#12]
After the successful login, it shows 
field "lovedLanguagesByname_aggregate" not found in type: 'programming_language'

**Comment by studuino** [comment]
missed to name object relationship name during setup.

**Comment by gbrcmg** [comment]
How did you solve it ?! 
I still have this error:
error:  {"message": "Unknown error", "name": "FormatedError", "originalError": {"code": "validation-failed", "error": "field \"lovedLanguagesByname_aggregate\" not found in type: 'programming_language'", "path": "$.selectionSet.programming_language.selectionSet.lovedLanguagesByname_aggregate"}}

already did relationships:
![image](https://user-images.githubusercontent.com/6237362/83820357-df54a280-a6a2-11ea-9dd3-8bc9b8df6a56.png)

![image](https://user-images.githubusercontent.com/6237362/83820343-d5cb3a80-a6a2-11ea-9289-5b6e962b8068.png)
